### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Jirsaacek** [TheBusyBiscuit/PrivateStorage#6]
[Fri, 24. Jul 2020 12:23:23 CEST ERROR] Could not pass event PlayerInteractEvent to Slimefun vDEV - 590 (git ee62a9b0)

Getting this error when player is trying to open chest from this addon.
Don't know what can cause that :/
![Screenshot_20200723-150050_Samsung_Internet](https://user-images.githubusercontent.com/63473875/88382593-0da05580-cda9-11ea-87ef-3c45b2d0f744.jpg)
![Screenshot_20200723-150021_Samsung_Internet](https://user-images.githubusercontent.com/63473875/88382597-0f6a1900-cda9-11ea-8eb6-39e80ca169f1.jpg)

**Comment by Jirsaacek** [comment]
Can you at least say something before just closing this topic please? Maybe why? 😂

**Comment by TheBusyBiscuit** [comment]
If you encounter an error, post the full error.
Saying there is an error without even including the actual stacktrace is just useless.

**Comment by Jirsaacek** [comment]
[2020-07-27-3.log](https://github.com/TheBusyBiscuit/PrivateStorage/files/4987972/2020-07-27-3.log)

There you go 😃
