### ISSUE TITLE
wrong chest drop

### ISSUE THREAD

**Issue by 100petr** [TheBusyBiscuit/PrivateStorage#7]
## Description (Required)

The destroyed chest will not drop properly.
## Steps to reproduce the Issue (Required)

Place emerald chest
Destroy it (as player)
it drop a cs-corelib's head
![image](https://user-images.githubusercontent.com/29830635/94266469-81421880-ff3a-11ea-9eb9-c2d6a52faa8d.png)

## Expected behavior (Required)

The chest will drop normally
## Server Log / Error Report

Error: https://pastebin.com/VawhaPPk
Full log: https://pastebin.com/MUCK0rSL
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/94266324-44762180-ff3a-11ea-860d-1f707ef207ff.png)

**Comment by LinoxGH** [comment]
> ## Description (Required)
> 
> 
> 
> The destroyed chest will not drop properly.
> ## Steps to reproduce the Issue (Required)
> 
> Place emerald chest
> Destroy it (as player)
> it drop a cs-corelib's head
> ![image](https://user-images.githubusercontent.com/29830635/94266469-81421880-ff3a-11ea-9eb9-c2d6a52faa8d.png)
> 
> ## Expected behavior (Required)
> 
> The chest will drop normally
> ## Server Log / Error Report
> 
> 
> Error: https://pastebin.com/VawhaPPk
> Full log: https://pastebin.com/MUCK0rSL
> ## Environment (Required)
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/29830635/94266324-44762180-ff3a-11ea-860d-1f707ef207ff.png)
> 
> 

Does this happen with or without `PrivateStorage.bypass` permission? Or both?

**Comment by 100petr** [comment]
If I give player this permission, it will drop right.

**Comment by LinoxGH** [comment]
Righto

**Comment by 100petr** [comment]
So should I just give this permissi to the players?

**Comment by LinoxGH** [comment]
Of course not this is a bug that I will fix soon
